spring:
  profiles:
    active: dev

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
#      packages-to-scan: com.easyauth

knife4j:
  enable: true
  setting:
    language: zh_cn

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/**/*.xml

secure:
  ignored:
    urls: #安全路径白名单
      - /user/auth/**
      - /admin/auth/**
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /favicon.ico
      - /webjars/**
      - /v3/api-docs/**
      - /error/**
